[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce75edff4ec640a757850bc28cbe7dd58cdee95e"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "375835a71f596dae4a428974b96566f972bf396cf5495f291f7b7ffa08a6dd49"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d68e31d3b229f0f4a2526fbacc13d11ebc7fc3db"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "ef2a4a65b5edbb1702889fad36c7dc80c0eb7298d17849901f5e5a8891d2be84"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17a2a9f2dc6a24d0acd279a1f566aef1f4273b63"
os = "windows"

    [[DssOpt.download]]
    sha256 = "897dfbc470eb52c796b12fe01a5876caec66bcd1dfba0d2451b70824c4bd6a21"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c3b50e7d364430f7b1e418eb18c09e1da11992b"
os = "windows"

    [[DssOpt.download]]
    sha256 = "4eb1c32fabff51d6980328e613c605152c5706512ef564311589b3c9c53416d3"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[DssOpt]]
arch = "aarch64"
git-tree-sha1 = "0377e2ae230ce39092d8bad23332e44222844383"
os = "macos"

    [[DssOpt.download]]
    sha256 = "6bf27a9bc856d9405eb12d8f4968ad733a0513d165dca0c60812d401393890fa"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.aarch64-apple-darwin.tar.gz"
[[DssOpt]]
arch = "aarch64"
git-tree-sha1 = "74c4dbd9fc19d623ccc30fbf66775cba230dfda8"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "ce24230d145ba1ebf56baac0ee6bcd55a766359c6ea8d244a698e1e1cb6b3ead"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.aarch64-linux-gnu.tar.gz"
[[DssOpt]]
arch = "aarch64"
git-tree-sha1 = "ea327c3048d7613c0abfb089c1b769183deb1d53"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "404de6cf4c625a0c2d1c933856a7ad1dbb6f5a2936814fc2e0c7ef187ec878c2"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.aarch64-linux-musl.tar.gz"
[[DssOpt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "97cfa96dcd0484f2d4a7a39df426c3850767ef01"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "7a44f1d5a7e3476773bcd4f6777f0f16f84e630778f4d0ea420088c72299c728"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.armv6l-linux-gnueabihf.tar.gz"
[[DssOpt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "214faa5f2ab1d406a5b910248542282a49b54283"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "e8adb379116e04c5b2ce493ddbcb9c031de775eded57e8c93bd269db6fe26ab7"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.armv6l-linux-musleabihf.tar.gz"
[[DssOpt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c8225e31fa4aa6599babc28b3fb463bf3eda270"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "092e7faca514ef9191fada464b29f10f385d1874073edc2ee84a353fb44a6dba"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.armv7l-linux-gnueabihf.tar.gz"
[[DssOpt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "71e9ac0aff72a4fea703c1e47a7a0731a5d40974"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "c294f96e6a4d2b8859a186f223fec064bc6f0d208f50d5d4532250a3dc90567a"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.armv7l-linux-musleabihf.tar.gz"
[[DssOpt]]
arch = "i686"
git-tree-sha1 = "f3bd22b6d936f4b1878d821f7e28b4466609d1ef"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "b4fbc918ac35ce6b15ff63e78a154839695135871edc4544a5e5004d54e10b7c"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.i686-linux-gnu.tar.gz"
[[DssOpt]]
arch = "i686"
git-tree-sha1 = "815c0c1429f90b57df3cd2e9b6a1147f04094bbc"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "bdf093638ee7b8471c0a03149625a972826111e32b3b7636f3cf37c7bdf066c0"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.i686-linux-musl.tar.gz"
[[DssOpt]]
arch = "i686"
git-tree-sha1 = "0bdf620fefb1197bdf9a895e68b9248335971d1e"
os = "windows"

    [[DssOpt.download]]
    sha256 = "d05e6d9d524175a6a9bef5ec6207922e4dcb1e585562a9d28b15265b458bf38e"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.i686-w64-mingw32.tar.gz"
[[DssOpt]]
arch = "powerpc64le"
git-tree-sha1 = "3f2bdf5a793b3eeab02aeabf0253bb39f632cf40"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "84eda34d49b4c5f0bd705ffcae62cfc2690581c5edc2e1e76fa29f18cddfc8cd"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.powerpc64le-linux-gnu.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "3cad355ea1499e8fb941669bf9c7fcdff606e1d5"
os = "macos"

    [[DssOpt.download]]
    sha256 = "7a69dbe367537327408d2240e2779b55ce00b71b367a8502a0cae7eec9bca74a"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.x86_64-apple-darwin.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "49d10aca543f00af69b39b441186c1e69f7f85cf"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "65c28761149c8719d1c4d498e365ba628ec5008bacda93412e6b415cf831d204"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.x86_64-linux-gnu.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "0de3d842f5617000dd18c551a55f99e8b2ff760e"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "e48bdc87d9fc64d2a1987cf982eac75d9d88450d7f3a858fcd0ef6769f5a36d7"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.x86_64-linux-musl.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "a190ee8e5a024f572ce66dd7fb617a1886982039"
os = "freebsd"

    [[DssOpt.download]]
    sha256 = "8e3ebca477c33f848865b6526d9acf53ec9d7488c5103c18a7d1c1d5ac91b4bb"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.x86_64-unknown-freebsd.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "652f3660e981e2251548944ee892b01924058896"
os = "windows"

    [[DssOpt.download]]
    sha256 = "095abcba79547a92105cc340518e0dee01906fa71e5398072124b1e106c50b6e"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.3+0/DssOpt.v1.0.3.x86_64-w64-mingw32.tar.gz"
