[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce75edff4ec640a757850bc28cbe7dd58cdee95e"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "375835a71f596dae4a428974b96566f972bf396cf5495f291f7b7ffa08a6dd49"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d68e31d3b229f0f4a2526fbacc13d11ebc7fc3db"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "ef2a4a65b5edbb1702889fad36c7dc80c0eb7298d17849901f5e5a8891d2be84"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17a2a9f2dc6a24d0acd279a1f566aef1f4273b63"
os = "windows"

    [[DssOpt.download]]
    sha256 = "897dfbc470eb52c796b12fe01a5876caec66bcd1dfba0d2451b70824c4bd6a21"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c3b50e7d364430f7b1e418eb18c09e1da11992b"
os = "windows"

    [[DssOpt.download]]
    sha256 = "4eb1c32fabff51d6980328e613c605152c5706512ef564311589b3c9c53416d3"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[DssOpt]]
arch = "aarch64"
git-tree-sha1 = "228940b4b5736fbb5b86bd6c7e416469dc733030"
os = "macos"

    [[DssOpt.download]]
    sha256 = "550a30baad55fe1eadb3601363220cfa3586000ad7855b5d756d31cf6e205540"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.aarch64-apple-darwin.tar.gz"
[[DssOpt]]
arch = "aarch64"
git-tree-sha1 = "d5d8d1bd1b827ab8ffb69b8e88f70a0bc75e23b0"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "817daa70461b4672c0a510a8e414ba1496f6c33146a0d2703d7cb24e552a7d6f"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.aarch64-linux-gnu.tar.gz"
[[DssOpt]]
arch = "aarch64"
git-tree-sha1 = "8497de5bb7b8752bb8dc63da4563e4f1650d10db"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "59238247685ace1c6530a6e1aaace2a899783fe02153824f4463ae1618a7af4b"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.aarch64-linux-musl.tar.gz"
[[DssOpt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "73a0724d7cde4a7cbaec125f72a42788d8d8597e"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "0e49c3e2a4b9fca51b1629cfbc3deb13c7eee7b5bf46feb5375ab3d317a1d8b6"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.armv6l-linux-gnueabihf.tar.gz"
[[DssOpt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d1f313fd082051a10ad481fda850f565cde70dc"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "62990c1080c0f341ce440e40be3f0672c737f65ed53d211ea33c117df955061c"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.armv6l-linux-musleabihf.tar.gz"
[[DssOpt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "edf0cc43e422842e611dc0b6761cc7e402f979d8"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "4f4e09e6ed4a052ed4983e6152540c9547bdf996067a9f7b4582a96316e0b18b"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.armv7l-linux-gnueabihf.tar.gz"
[[DssOpt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa9916a0625e7a6e57b3d307f6016d0a317f946b"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "987610e11a42e9fa171fb5c91034a3fbede8cd2985f4ed09acfbc7ce1ebef8e9"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.armv7l-linux-musleabihf.tar.gz"
[[DssOpt]]
arch = "i686"
git-tree-sha1 = "2f0de3c0b456eb4070cbb19914f52e5c65c3ff4f"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "533a98b4aeb8c1d36bab35339b16d7854753f791cb617d4bcf88b1c2fe066b4e"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.i686-linux-gnu.tar.gz"
[[DssOpt]]
arch = "i686"
git-tree-sha1 = "df1a70d90dcb6b3173e0104b87b8e810dc71102a"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "f8f05e50e78cecc3f13d6f07a421950299515407832199bf0eec43039f191b7b"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.i686-linux-musl.tar.gz"
[[DssOpt]]
arch = "i686"
git-tree-sha1 = "aa55c6418b92729b7e33387c238da8f2f992bb3e"
os = "windows"

    [[DssOpt.download]]
    sha256 = "1c9a878d97fca6d7ca7bf1668b7b148e5df2a5c0d7e5036f48eb9d484739d81d"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.i686-w64-mingw32.tar.gz"
[[DssOpt]]
arch = "powerpc64le"
git-tree-sha1 = "f96ee7e2e478ff16f19a84e3ebd27c928bf3b1b8"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "22b4f390562c3dd2656f6375f3912fc056b3aadd67123a699a0746ffcdff51d4"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.powerpc64le-linux-gnu.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "3a008142238a16bfff97c925069a526cd0848073"
os = "macos"

    [[DssOpt.download]]
    sha256 = "b4de07414d4a9eb5ae33d618c550147fe04e768d088350ed6f541819199f30e0"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.x86_64-apple-darwin.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "f6bbcf7e4a8622cd7a58127ed309f6b8edba93f1"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "b7c6f7cc7983792162914ee9b886c4445c482fbab0ae3b485ee79762c849ea82"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.x86_64-linux-gnu.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "50d6c9f5bafad5d046db688fbc8ed0c067d476ea"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "8d8c407fedc82789e7f78367e869e496109f09c598a48052319076f7d2ba5be8"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.x86_64-linux-musl.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "df09c2038e8073bb06b140ddeda6e88244e76d0a"
os = "freebsd"

    [[DssOpt.download]]
    sha256 = "23ad0b20af972971dfeaaa3c91dc39d79b1d3b6c9c6682b1670e2a11451bf281"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.x86_64-unknown-freebsd.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "d38daaafaf2f0c46decfa53979c5c92ff111d355"
os = "windows"

    [[DssOpt.download]]
    sha256 = "79ae10fa2c410b82468f7f30bbf946d68cd3ea8515f71dc64fcd9e1c58b1b010"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.5+0/DssOpt.v1.0.5.x86_64-w64-mingw32.tar.gz"
