[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce75edff4ec640a757850bc28cbe7dd58cdee95e"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "375835a71f596dae4a428974b96566f972bf396cf5495f291f7b7ffa08a6dd49"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d68e31d3b229f0f4a2526fbacc13d11ebc7fc3db"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "ef2a4a65b5edbb1702889fad36c7dc80c0eb7298d17849901f5e5a8891d2be84"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17a2a9f2dc6a24d0acd279a1f566aef1f4273b63"
os = "windows"

    [[DssOpt.download]]
    sha256 = "897dfbc470eb52c796b12fe01a5876caec66bcd1dfba0d2451b70824c4bd6a21"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[DssOpt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c3b50e7d364430f7b1e418eb18c09e1da11992b"
os = "windows"

    [[DssOpt.download]]
    sha256 = "4eb1c32fabff51d6980328e613c605152c5706512ef564311589b3c9c53416d3"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.1+0/DssOpt.v1.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[DssOpt]]
arch = "aarch64"
git-tree-sha1 = "02baaacb798bfcfaf6f6efc734e0c45662aacf3a"
os = "macos"

    [[DssOpt.download]]
    sha256 = "274f1edec22b6651e1b0ce60c6332a0d56cd03ad18fcca1133dd63c2fbe07dcc"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.aarch64-apple-darwin.tar.gz"
[[DssOpt]]
arch = "aarch64"
git-tree-sha1 = "f67bee5a2221bbfb44c26e5dd6721f76bebcbc6f"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "1e2875304f5cd9fae83404cc8d877dd1a6ebc9d2d9b6df1815c658ef1443e681"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.aarch64-linux-gnu.tar.gz"
[[DssOpt]]
arch = "aarch64"
git-tree-sha1 = "6f956d0be5bf66c60eb091a309f4456e786236e2"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "da34b489ea274e0cd6e014f64ccff6a26a5fd082e9fe81553d64f5546c448bfe"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.aarch64-linux-musl.tar.gz"
[[DssOpt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "90cb7fd390ca06d1a96e9c75346a390831cc4341"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "5c76b158b810d00ccd565bb2ea98382094da595776f51aa4e72ee7407e9c0b1e"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.armv6l-linux-gnueabihf.tar.gz"
[[DssOpt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "27406277c1d95f67a7ac202118e9dee720435328"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "fcd687d6c1f35c1073f3d30557a0b5bfcf162454e65ec13e338ae3a8dc4746d4"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.armv6l-linux-musleabihf.tar.gz"
[[DssOpt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8ecd2741fe846669cbd28e4595148a2037c0701a"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "9a93e02ee20a876c4d27e9c43d0056ba26d4e37a35d4b16b1bf40b7d8e2b7c23"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.armv7l-linux-gnueabihf.tar.gz"
[[DssOpt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d4b085b2df14876e4be206f9fd6710731529264c"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "48db8718f8266f06c816d26d1c82c5677f0e244ae09315c519e7a8d7d2179a96"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.armv7l-linux-musleabihf.tar.gz"
[[DssOpt]]
arch = "i686"
git-tree-sha1 = "d29a1ae88f956e8ca957abc862d3195a8794c08f"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "1ad6b47bdee32923654a00582006239a3074eab12f964ca0a7cfb110e99ed41a"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.i686-linux-gnu.tar.gz"
[[DssOpt]]
arch = "i686"
git-tree-sha1 = "822a979511ce111c933e321c799a0082c9ce523e"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "562ef88056bca529d8b4898bed3cc9713d8ce3007639c2b1a0405a7b58aacdf5"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.i686-linux-musl.tar.gz"
[[DssOpt]]
arch = "i686"
git-tree-sha1 = "d32c29a8ade67375e9fa2440cbb33fb1e9217eeb"
os = "windows"

    [[DssOpt.download]]
    sha256 = "fefe12fdd3d467868f2a2eea5671dbc998cc40f38322853f798f0421da7d25bb"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.i686-w64-mingw32.tar.gz"
[[DssOpt]]
arch = "powerpc64le"
git-tree-sha1 = "98a68c45aa68c8f387f3adfdb192ed20c4507ce1"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "ad49f5001ee04e93552dde2b305d8449fd5986ab32193817e40a462123d98155"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.powerpc64le-linux-gnu.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "bf024e29c7e01b2b419ac1987b26fb208d179fa4"
os = "macos"

    [[DssOpt.download]]
    sha256 = "9e83b9fe1502eb3983fc8e7e5b189c7b73fe019eefa53c32b094221222e654c7"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.x86_64-apple-darwin.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "2da15b1fddd656b5fdedb34fdb0710be89785640"
libc = "glibc"
os = "linux"

    [[DssOpt.download]]
    sha256 = "14b774c35bc8058c0bede1c6d96e5c62f2febfad36e767c5a329aa80b22221ea"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.x86_64-linux-gnu.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "80434cd6c9e576b5f3aaa660ed4f90f9ba28d690"
libc = "musl"
os = "linux"

    [[DssOpt.download]]
    sha256 = "3a90cac1328c5e3d8fa6c986cf8474b741db5f3ba5fc3fba3a8ab7c4db0dca5e"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.x86_64-linux-musl.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "eb46d85cfe7d4f0d064b753b6491cfa685251438"
os = "freebsd"

    [[DssOpt.download]]
    sha256 = "3487aef88af8dcc5c93589625db9ef7c1c6c2caa0b4339256ecb8924ba1d4ae4"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.x86_64-unknown-freebsd.tar.gz"
[[DssOpt]]
arch = "x86_64"
git-tree-sha1 = "d029d24e43880c39958479a6b519f6fd82d13ea2"
os = "windows"

    [[DssOpt.download]]
    sha256 = "945d51a7f42bda8bd0364763960885e13a647ee9908707e4d7fba0a0a2853001"
    url = "https://github.com/marcom/DssOpt_jll.jl/releases/download/DssOpt-v1.0.4+0/DssOpt.v1.0.4.x86_64-w64-mingw32.tar.gz"
